@tool
extends EditorScript

# This script assembles the "VikingDynastyTheme.tres" using the assets
# generated by UIAssetGen.gd.

const THEME_PATH = "res://ui/themes/VikingDynastyTheme.tres"
const ASSET_PATH = "res://ui/assets/"
const FONT_PATH = "res://assets/fonts/"

# Colors
const COL_INK = Color("#2b221b")
const COL_PARCHMENT = Color("#f5e6d3")
const COL_GOLD = Color("#c5a54e")

func _run() -> void:
	print("--- Building Chronicler Theme ---")
	
	# 1. Create or Load Theme
	var theme = Theme.new()
	
	# 2. Load Fonts (with fallbacks)
	var font_header = _try_load_font("UncialAntiqua-Regular.ttf")
	var font_body = _try_load_font("CrimsonText-Regular.ttf")
	
	if font_header:
		theme.set_default_font(font_body)
		theme.set_default_font_size(20)
	
	# --- BUTTON STYLING (Wood) ---
	var wood_tex = load(ASSET_PATH + "wood_bg.png")
	if wood_tex:
		var style_normal = StyleBoxTexture.new()
		style_normal.texture = wood_tex
		style_normal.modulate_color = Color.WHITE
		# Add margins so text doesn't hit the edge
		style_normal.content_margin_left = 10
		style_normal.content_margin_right = 10
		style_normal.content_margin_top = 5
		style_normal.content_margin_bottom = 5
		
		var style_hover = style_normal.duplicate()
		style_hover.modulate_color = Color(1.2, 1.2, 1.2) # Lighter
		
		var style_pressed = style_normal.duplicate()
		style_pressed.modulate_color = Color(0.8, 0.8, 0.8) # Darker
		
		var style_disabled = style_normal.duplicate()
		style_disabled.modulate_color = Color(0.5, 0.5, 0.5) # Greyed out

		theme.set_stylebox("normal", "Button", style_normal)
		theme.set_stylebox("hover", "Button", style_hover)
		theme.set_stylebox("pressed", "Button", style_pressed)
		theme.set_stylebox("disabled", "Button", style_disabled)
		
		# Button Text Colors
		theme.set_color("font_color", "Button", COL_PARCHMENT)
		theme.set_color("font_hover_color", "Button", Color.WHITE)
		theme.set_font("font", "Button", font_header)
		theme.set_font_size("font_size", "Button", 20)

	# --- PANEL CONTAINER (Parchment) ---
	var parchment_tex = load(ASSET_PATH + "parchment_bg.png")
	if parchment_tex:
		var style_panel = StyleBoxTexture.new()
		style_panel.texture = parchment_tex
		style_panel.axis_stretch_horizontal = StyleBoxTexture.AXIS_STRETCH_MODE_TILE
		style_panel.axis_stretch_vertical = StyleBoxTexture.AXIS_STRETCH_MODE_TILE
		# Margins
		style_panel.content_margin_left = 20
		style_panel.content_margin_right = 20
		style_panel.content_margin_top = 20
		style_panel.content_margin_bottom = 20
		
		theme.set_stylebox("panel", "PanelContainer", style_panel)

	# --- LABELS (Ink) ---
	theme.set_color("font_color", "Label", COL_INK)
	theme.set_color("default_color", "RichTextLabel", COL_INK)
	
	# --- HEADER LABEL VARIATION ---
	# Usage: Add "Header" to the Label's theme_type_variation property
	theme.set_font("font", "HeaderLabel", font_header)
	theme.set_font_size("font_size", "HeaderLabel", 24)
	theme.set_color("font_color", "HeaderLabel", COL_INK)
# --- RESOURCE TAG VARIATION (Dark Plaque) ---
	var tag_tex = load(ASSET_PATH + "resource_tag.png")
	if tag_tex:
		var style_tag = StyleBoxTexture.new()
		style_tag.texture = tag_tex
		# Margins to give the text breathing room inside the box
		style_tag.content_margin_left = 12
		style_tag.content_margin_right = 12
		style_tag.content_margin_top = 8
		style_tag.content_margin_bottom = 4
		
		# Define the variation
		theme.set_stylebox("normal", "ResourceLabel", style_tag)
		theme.set_color("font_color", "ResourceLabel", COL_PARCHMENT) # Light text
		theme.set_font("font", "ResourceLabel", font_header) # Use the Fancy Font
		theme.set_font_size("font_size", "ResourceLabel", 24) # Bigger!
	# --- TOOLTIP ---
	var tooltip_tex = load(ASSET_PATH + "tooltip_bg.png")
	if tooltip_tex:
		var style_tooltip = StyleBoxTexture.new()
		style_tooltip.texture = tooltip_tex
		style_tooltip.content_margin_left = 10
		style_tooltip.content_margin_right = 10
		style_tooltip.content_margin_top = 5
		style_tooltip.content_margin_bottom = 5
		
		# TooltipPanel is the background
		theme.set_stylebox("panel", "TooltipPanel", style_tooltip)
		
		# TooltipLabel is the text
		theme.set_color("font_color", "TooltipLabel", Color.WHITE)
		theme.set_font_size("font_size", "TooltipLabel", 18)
	# --- SAVE ---
	if not DirAccess.dir_exists_absolute(THEME_PATH.get_base_dir()):
		DirAccess.make_dir_recursive_absolute(THEME_PATH.get_base_dir())
		
	var error = ResourceSaver.save(theme, THEME_PATH)
	if error == OK:
		print("Theme saved to: ", THEME_PATH)
	else:
		print("Error saving theme: ", error)
		
	EditorInterface.get_resource_filesystem().scan()

func _try_load_font(filename: String) -> Font:
	var path = FONT_PATH + filename
	if ResourceLoader.exists(path):
		return load(path)
	print("Warning: Font not found at ", path, ". Using default.")
	return ThemeDB.get_fallback_font()
